"use client";

import React from "react";
import { motion } from "framer-motion";
import {
  FileText,
  Shield,
  Cpu,
  Database,
  ArrowRight,
  ChevronRight,
  AlertCircle
} from "lucide-react";
import Navbar from "@/app/components/layout/Navbar";
import Footer from "@/app/components/layout/Footer";
import DarkVeil from "@/app/components/effects/DarkVeil";
import ShinyText from "@/components/ui/ShinyText";

export default function TermsOfServicePage() {
  const terms = [
    {
      title: "1. Scope of the Application License",
      icon: <Cpu className="h-5 w-5 text-[var(--accent-primary)]" />,
      content: "Strat Ai is a local desktop analytical terminal. When downloading our binaries, you are granted a non-transferable, revocable license to run our calculations locally on your own CPU/GPU for Indian F&O and global Crypto. We do not operate cloud servers, hold funds, or provide automated execution.",
    },
    {
      title: "2. User-Provided API Subscriptions",
      icon: <Database className="h-5 w-5 text-[var(--accent-primary)]" />,
      content: "To utilize the real-time ingest pipeline, you must bind your own official broker credentials (e.g. Zerodha Kite Connect API key and secrets) or direct Crypto exchange WebSockets. You are solely responsible for paying subscription fees, managing rate limits, and securing your key parameters locally.",
    },
    {
      title: "3. Algorithmic Signals and Disclaimers",
      icon: <Shield className="h-5 w-5 text-[var(--accent-primary)]" />,
      content: "All technical metrics, Bollinger Bands, CMF trend indices, OLS Ghost Lines, and DeepSeek insights generated by the terminal are mathematical indicators for study only. They are not direct trade triggers or execution orders. All transactions must be manually submitted.",
    },
    {
      title: "4. Technical Liability Limitations",
      icon: <AlertCircle className="h-5 w-5 text-[var(--accent-primary)]" />,
      content: "Because the application runs entirely on your local workstation, Strat Ai is not liable for financial outcomes resulting from local hardware crashes, network interface lag, Redpanda buffer backpressure, QuestDB disk failures, or broker and exchange gateway drops.",
    },
  ];

  return (
    <>
      {/* Background DarkVeil CRT scanline layer */}
      <div className="fixed inset-0 pointer-events-none -z-50 opacity-[0.22]">
        <DarkVeil speed={0.15} noiseIntensity={0.01} scanlineIntensity={0.08} scanlineFrequency={1.2} />
      </div>

      {/* Dotted pattern */}
      <div className="absolute inset-0 pointer-events-none opacity-[0.06] bg-dot-grid -z-40" />

      {/* Decorative Background Orbs */}
      <div className="absolute top-[10%] left-[4%] w-[40rem] h-[40rem] rounded-full orb-emerald opacity-30 pointer-events-none -z-30" />
      <div className="absolute top-[40%] right-[4%] w-[35rem] h-[35rem] rounded-full orb-purple opacity-20 pointer-events-none -z-30" />

      <Navbar />

      <main className="flex-grow pt-28 md:pt-36 pb-24">
        {/* Centered Hero Section */}
        <section className="relative mx-auto max-w-[80rem] px-6 text-center md:px-8 pt-10 pb-12 flex flex-col items-center">
          <motion.div
            initial={{ opacity: 0, y: -12 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ duration: 0.5, ease: [0.16, 1, 0.3, 1] }}
            className="backdrop-filter-[12px] inline-flex h-8 items-center justify-between rounded-full border border-white/5 bg-white/10 px-4 text-xs text-white transition-all ease-in hover:cursor-pointer hover:bg-white/20 group gap-2 mb-8 cursor-pointer select-none"
          >
            <ShinyText
              text="⚖️ SOFTWARE LICENSE & USER COMPLIANCE"
              className="inline-flex items-center justify-center text-[10px] font-mono tracking-widest font-bold text-[var(--accent-primary)] uppercase"
            />
            <ArrowRight className="h-3 w-3 text-[var(--accent-primary)] transition-transform duration-300 group-hover:translate-x-0.5" />
          </motion.div>

          <motion.h1
            initial={{ opacity: 0, y: 12 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ delay: 0.1, duration: 0.5, ease: [0.16, 1, 0.3, 1] }}
            className="text-[var(--text-primary)] py-4 text-4xl font-bold leading-[1.1] tracking-tighter text-balance sm:text-6xl md:text-7xl lg:text-8xl font-heading"
          >
            Terms of Service
          </motion.h1>

          <motion.p
            initial={{ opacity: 0, y: 12 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ delay: 0.2, duration: 0.5, ease: [0.16, 1, 0.3, 1] }}
            className="text-xs sm:text-sm md:text-base text-[var(--text-secondary)] leading-relaxed max-w-2xl text-balance"
          >
            Last updated: May 22, 2026. Please read the license parameters, technical limitations, and compliance responsibilities of compiling or executing the Strat Ai terminal.
          </motion.p>
        </section>

        {/* Content Section */}
        <section className="relative mx-auto max-w-[55rem] px-6 md:px-8">
          <motion.div
            initial={{ opacity: 0, y: 20 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ delay: 0.3, duration: 0.5 }}
            className="space-y-10"
          >
            {/* Introductory Notice */}
            <div className="glass border border-[var(--border-subtle)] rounded-xl p-6 relative overflow-hidden">
              <div className="absolute top-0 right-0 w-24 h-24 orb-emerald opacity-10 pointer-events-none" />
              <p className="text-xs text-[var(--text-secondary)] leading-relaxed">
                Welcome to Strat Ai. By downloading, packaging, compiling, or executing our local software client, you agree to comply with and be bound by the following terms, conditions, and software licensing provisions. If you do not agree, please terminate your local session and delete all downloaded binaries immediately.
              </p>
            </div>

            {/* Terms List Grid */}
            <div className="space-y-6">
              {terms.map((t, idx) => (
                <div
                  key={idx}
                  className="relative rounded-xl border border-[var(--border-subtle)] bg-[var(--bg-card)] p-6 overflow-hidden group hover:border-[rgba(16,185,129,0.25)] transition-all duration-300"
                >
                  {/* Border Beam emulation */}
                  <div className="absolute -inset-[2px] rounded-xl bg-[conic-gradient(from_0deg,transparent_40%,var(--accent-primary)_50%,transparent_60%)] opacity-0 group-hover:opacity-100 -z-10 animate-[spin_10s_linear_infinite] transition-opacity duration-500 pointer-events-none" />
                  <div className="absolute inset-[1px] bg-[var(--bg-card)] rounded-[11px] -z-10 pointer-events-none" />

                  <div className="flex items-start gap-4">
                    <div className="p-2.5 rounded-lg bg-[var(--accent-soft)] border border-[rgba(16,185,129,0.1)] text-[var(--accent-primary)] flex-shrink-0 group-hover:scale-105 transition-transform duration-300">
                      {t.icon}
                    </div>
                    <div>
                      <h3 className="font-semibold font-heading text-sm text-[var(--text-primary)] mb-2">
                        {t.title}
                      </h3>
                      <p className="text-xs text-[var(--text-secondary)] leading-relaxed">
                        {t.content}
                      </p>
                    </div>
                  </div>
                </div>
              ))}
            </div>

            {/* Back to home terminal */}
            <div className="flex justify-center pt-4">
              <a
                href="/"
                className="inline-flex items-center justify-center px-6 py-3 rounded-md border border-[var(--border-subtle)] hover:border-[var(--accent-primary)] hover:bg-[var(--accent-soft)] text-[var(--text-primary)] hover:text-white font-bold text-xs tracking-wider uppercase transition-all duration-200 gap-2"
              >
                <span>Back to Home Terminal</span>
                <ChevronRight className="h-4 w-4" />
              </a>
            </div>
          </motion.div>
        </section>
      </main>

      <Footer />
    </>
  );
}

