import React from "react";
import SubpageLayout from "@/app/components/layout/SubpageLayout";

export default function TermsOfServicePage() {
  const terms = [
    {
      title: "1. Scope of the Application License",
      content: "Strat is a local desktop analytical terminal. When downloading our binaries, you are granted a non-transferable, revocable license to run our calculations locally on your own CPU. We do not provide brokerage accounts, pooled fund custody, or execution servers.",
    },
    {
      title: "2. User-Provided API Subscriptions",
      content: "To utilize the real-time ingest pipeline, you must bind your own official broker credentials (e.g., Zerodha Kite Connect API key and secrets). You are solely responsible for paying subscription fees to your broker, managing rate limits, and securing your access key parameters.",
    },
    {
      title: "3. Algorithmic Signals and Disclaimers",
      content: "All technical metrics, Bollinger Bands, CMF trend indices, OLS Ghost Lines, and DeepSeek insights generated by the terminal are mathematical indicators for reference. They are not direct trade triggers or execution orders. All transactions must be manually submitted or reviewed by the user; we do not operate auto-trading bots.",
    },
    {
      title: "4. Technical Liability Limitations",
      content: "Because the application runs on your local workstation, Strat is not liable for financial outcomes resulting from local hardware crashes, network interface lag, Redpanda buffer backpressure, QuestDB disk failures, or broker websocket gateway drops.",
    },
  ];

  return (
    <SubpageLayout
      title="Terms of Service"
      subtitle="Last updated: May 22, 2026. Read the software license parameters and operational terms of the Strat terminal."
      category="Legal"
    >
      <div className="max-w-3xl space-y-8 pb-8">
        <p className="text-xs text-[var(--text-muted)] leading-relaxed">
          Welcome to Strat. By downloading, compiling, or executing our software shells, you agree to comply with and be bound by the following terms and licensing provisions.
        </p>

        <div className="space-y-8 mt-6">
          {terms.map((t, idx) => (
            <div key={idx} className="space-y-3">
              <h3 className="text-sm font-bold font-heading text-[var(--text-primary)]">
                {t.title}
              </h3>
              <p className="text-xs text-[var(--text-muted)] leading-relaxed">
                {t.content}
              </p>
            </div>
          ))}
        </div>
      </div>
    </SubpageLayout>
  );
}
