import React from "react";
import SubpageLayout from "@/app/components/layout/SubpageLayout";

export default function DisclaimerPage() {
  return (
    <SubpageLayout
      title="Regulatory Disclaimer & Risk Disclosures"
      subtitle="Last updated: May 22, 2026. Important compliance guidelines, SEBI regulations, and market risk statements."
      category="Legal"
    >
      <div className="max-w-3xl space-y-8 pb-8">
        {/* SEBI F&O Mandatory Warning Box */}
        <div className="border border-[var(--border-gold)] bg-[var(--gold-soft)] rounded-xl p-5 md:p-6 space-y-3">
          <span className="text-[10px] font-mono text-[var(--gold-primary)] font-bold tracking-widest block uppercase">
            ⚠️ SEBI Mandatory Disclosure for Futures & Options
          </span>
          <p className="text-xs text-[var(--text-muted)] leading-relaxed">
            9 out of 10 individual traders in equity Futures and Options (F&O) segment incurred net losses. On average, loss makers registered net trading loss close to ₹50,000. Over and above the net trading losses incurred, loss makers expended an additional 28% of net trading losses as transaction costs. Those making net profits represent less than 11% of active accounts.
          </p>
        </div>

        <div className="space-y-6">
          <div className="space-y-2.5">
            <h3 className="text-sm font-bold font-heading text-[var(--text-primary)]">
              1. Non-Broker & Non-Advisory Operations
            </h3>
            <p className="text-xs text-[var(--text-muted)] leading-relaxed">
              Alpha Suite is a **software terminal for analytics and indicators**. We do **not act as a SEBI-registered Investment Advisor (RIA)**, a Research Analyst, or a stock broker. We do **not provide financial advisory**, portfolio management, or trade execution services. The terminal is a localized dashboard designed for user-directed research and manual execution.
            </p>
          </div>

          <div className="space-y-2.5">
            <h3 className="text-sm font-bold font-heading text-[var(--text-primary)]">
              2. Technical Indicator & Model Warnings
            </h3>
            <p className="text-xs text-[var(--text-muted)] leading-relaxed">
              All computations (including RSI, VWAP, Bollinger Bands, CMF trend gauges, OLS Ghost Lines, and DeepSeek insights) are generated by local algorithms from raw historical or streaming feed ticks. These mathematical calculations are for study only and do not guarantee profits. Past simulated backtests are not indicators of future market returns.
            </p>
          </div>

          <div className="space-y-2.5">
            <h3 className="text-sm font-bold font-heading text-[var(--text-primary)]">
              3. Algorithmic Execution Responsibilities
            </h3>
            <p className="text-xs text-[var(--text-muted)] leading-relaxed">
              Alpha Suite does not support pooled-funds, automated copy-trading, or unsupervised execution bots. Any strategy routing or indicators evaluations must be validated manually by the user. The user is solely responsible for getting required regulatory approvals from exchanges if they choose to link indicators directly to broker order APIs.
            </p>
          </div>
        </div>
      </div>
    </SubpageLayout>
  );
}
